### ISSUE TITLE
Describe new migrations approach

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce-Docs#100]
A new article about migrations in 4.30 - "How do migrations work?"

Let's put it under "Developer guide" > "Developer tutorials" right after the "How do I register new routes?" article

Also check - https://www.nopcommerce.com/en/boards/topic/81549/nopcommerce-43-beta-fluent-migrator-workflow#264686

**Comment by AndreiMaz** [comment]
@skoshelev also check https://www.nopcommerce.com/en/boards/topic/81549/nopcommerce-43-beta-fluent-migrator-workflow#264686

**Comment by skoshelev** [comment]
You may found the new topic [here](https://docs.nopcommerce.com/en/developer/tutorials/migrations.html)

Closed #100
