### ISSUE TITLE
Update "How to code my own payment method" and "How to code my own shipping rate computation method"

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce-Docs#103]
Articles - https://docs.nopcommerce.com/en/developer/plugins/payment-method.html and https://docs.nopcommerce.com/en/developer/plugins/shipping-plugin.html

Update it according to development changes in 4.30

P.S. They also reference "How to write a plugin for nopCommerce 4.20" article that should be replaced with a new one for 4.30 - https://github.com/nopSolutions/nopCommerce-Docs/issues/95

**Comment by skoshelev** [comment]
Closed #103
