### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce-Docs#13]
Right now almost all pages have outdated screenshots. We need to update them according to the latest version of nopCommerce

For example, on some pages you can still see tabs instead of panels we've starting using in nopCommerce 4.20. Example - https://docs.nopcommerce.com/user-guide/running/product-management/categories.html

**Comment by DmitriyKulagin** [comment]
Here is a list of pages that still need screenshot updates:
 - https://docs.nopcommerce.com/user-guide/configuring/settingup/shipping/providers/manual/fixed-rate-methods.html
 - https://docs.nopcommerce.com/user-guide/configuring/settingup/shipping/providers/manual/fixed-rate-restrictions.html
 - https://docs.nopcommerce.com/user-guide/configuring/settingup/shipping/providers/manual/methods.html

**Comment by rajupaladiya** [comment]
@DmitriyKulagin - I'm already working on rest of pages.

Once done will send pull request.
Thank You
