### ISSUE TITLE
Guide to creating a page containing a reporting table of DataTables

### ISSUE THREAD

**Issue by DmitriyKulagin** [nopSolutions/nopCommerce-Docs#2]
The main task of the tutorial is to show how you can expand the functionality of the admin panel. It is proposed to consider the implementation of the page containing the table displaying information on the distribution of users by country (based on the billing address) step by step.

**Comment by nopsg** [comment]
how to submit the doc?

**Comment by DmitriyKulagin** [comment]
Hi, @nopsg 
Please, see this doc: https://github.com/nopSolutions/nopCommerce-Docs/blob/master/CONTRIBUTING.md
