### ISSUE TITLE
Wrong file name

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce-Docs#20]
https://github.com/nopSolutions/nopCommerce-Docs/blob/master/developer/plugins/shippng-plugin.md should be shipping-plugin.md (missing "i")

**Comment by exileDev** [comment]
Closed #20

**Comment by exileDev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Wrong file name](https://trello.com/c/4Gwe4VBF/557-wrong-file-name)
