### ISSUE TITLE
Fix links in developer documentation

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce-Docs#21]
1. A link is broken. Open https://docs.nopcommerce.com/developer/plugins/shippng-plugin.html and click "How to write a plugin for nopCommerce 4.20" link - it doesn't work

2. Actually it's hard-coded which is wrong. We should use "xref" and 'uid" or links but not direct links. For example, it's wrong in at https://docs.nopcommerce.com/developer/plugins/payment-method.html and  https://docs.nopcommerce.com/developer/plugins/shippng-plugin.html. It should be (xref:developer/plugins/how-to-write-plugin_4.20)

**Comment by exileDev** [comment]
Closed #21

**Comment by exileDev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix links in developer documentation](https://trello.com/c/joGh7dLk/558-fix-links-in-developer-documentation)
