### ISSUE TITLE
Rename "How to install and configure SSL certification" to "How to install and configure SSL certificates"

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce-Docs#222]
Page: https://docs.nopcommerce.com/en/getting-started/advanced-configuration/how-to-install-and-configure-ssl-certification.html

Do not forget to rename the article, menu element and page URL. Please note that it's referenced in the new "get started" wizard, so ensure that a previous URL works as well (redirects to a new one)

**Comment by DmitriyKulagin** [comment]
Closed #222
