### ISSUE TITLE
Clarification about reward points validity

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce-Docs#230]
> I see they have now added an expiration date, and it's set to 45 days by default. Is there a way to disable this setting so reward points never expire?

> I was just looking in documentation and google search but I could not find a reference. I did a quick test and I think if you set it to 0 then they wont expire ?

Source: https://www.nopcommerce.com/boards/topic/90782/remove-reward-points-expiration

**Comment by DmitriyKulagin** [comment]
Closed #230
