### ISSUE TITLE
Describe database naming convention

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce-Docs#237]
> Looking through tables we see some tables with `_` and others without. It looked like the `_` may be used for mapping tables but the `CustomerAddress` table is a mapping table without the `_`.  We are creating new tables and would like to follow NopCommerce Naming Conventions.

Source: https://www.nopcommerce.com/boards/topic/91670/database-naming-convention

**Comment by skoshelev** [comment]
Closed #237
