### ISSUE TITLE
Describe PayPal Commerce plugin

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce-Docs#239]
We use it now instead of PayPal Smart Payment Buttons

Let's replace and update the article - https://docs.nopcommerce.com/en/getting-started/configure-payments/payment-methods/paypal-smart-payment-buttons.html

Let's also add more info about the advanced settings of this plugin.

**Comment by AndreiMaz** [comment]
https://docs.nopcommerce.com/en/getting-started/configure-payments/payment-methods/paypal-commerce.html
