### ISSUE TITLE
Update "Docker" article (write about Docker Hub)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce-Docs#24]
Article - https://github.com/nopSolutions/nopCommerce-Docs/blob/master/developer/tutorials/docker.md

Add and describe information that nopCommerce is also available on Docker Hub at https://hub.docker.com/r/nopcommerceteam/nopcommerce

**Comment by maxpavlov** [comment]
Absolutely. Current docker doc is useless, it refers the Dockerfile on Step 3 which is nowhere to be found within the text of the article, casting it to be non-self contained.

**Comment by skoshelev** [comment]
Closed #24
