### ISSUE TITLE
Load active payment method

### ISSUE THREAD

**Issue by mrslyldrm** [nopSolutions/nopCommerce-Docs#245]
Hi,

I think PaymentPluginManager's LoadActivePluginsAsyncAsync method is not working right. When i filtered by countryId it is not include in query.  I think below in lambda expression "!" added as redundant.

            //filter by country
            if (countryId > 0)
                paymentMethods = await paymentMethods.WhereAwait(async method => !(await GetRestrictedCountryIdsAsync(method)).Contains(countryId)).ToListAsync();

**Comment by AndreiMaz** [comment]
It works fine
P.S. This repository is for documentation, not the main one - https://github.com/nopSolutions/nopCommerce

**Comment by mrslyldrm** [comment]
Sorry i had added my country to restrictedCountrys so it was not work right. it is works fine now
