### ISSUE TITLE
nopCommerce-Docs: Updating an Existing entity. Wrong NopMigration annotation

### ISSUE THREAD

**Issue by alex-dhanasekar-tw** [nopSolutions/nopCommerce-Docs#246]
In the documentation in the following URL : https://docs.nopcommerce.com/en/developer/tutorials/update-existing-entity.html

The code which is present in the migration class section : 

`[NopMigration("2020/05/25 11:24:16:2551770", "Category. Add some new property", MigrationProcessType.Installation)]`

Should be changed to 

`[NopMigration("2021/12/19 11:24:16:2551770", "Category. Add some new property", UpdateMigrationType.Data, MigrationProcessType.Update)]`

Otherwise, if we run the application as it is, we get the error, Cannot find property "SomeNewProperty" in database.

**Comment by AndreiMaz** [comment]
Also see https://www.nopcommerce.com/en/boards/topic/92763/adding-new-property-to-existing-entity#291088

**Comment by DmitriyKulagin** [comment]
Closed #246
