### ISSUE TITLE
Update migrations.md

### ISSUE THREAD

**Issue by lintho** [nopSolutions/nopCommerce-Docs#283]
This should be added somewhere in the docs:

**1. In order to run new migrations you have to increase the version in your plugin.json file**

**Comment by RomanovM** [comment]
See also:

> A new section can be considered in the nopCommerce documentation. It will help new developers to learn more quickly about plugins and also migration steps as well.

Source: https://www.nopcommerce.com/boards/topic/93998/official-documentation-of-plugin-version-migration

**Comment by DmitriyKulagin** [comment]
Closed #283
