### ISSUE TITLE
Guide how to start developing nopCommerce on Unix

### ISSUE THREAD

**Issue by DmitriyKulagin** [nopSolutions/nopCommerce-Docs#3]
Guidance should include:

1. The description is supposed to be divided into several options for using different operating systems - the first when it is supposed to be developed on Linux (Ubuntu 18.04), and macOS (Mojave, Catalina). Describe in steps what libraries are needed to run nopCommerce. For example, specify which version of the net core SDK should be used with links to download them, and so on. List how and in what order you need to install everything you need.
2. What are the basic tools a developer needs for the full development and debugging of nopCommerce (indicating the download links). For Linux, using Visual Studio Code as an example; for macOS, using Visual Studio for mac as an example. What settings and extensions are needed.
3. Describe the development capability through WSL.
4. Describe the debugging process, including debugging javaScript code on the client side
5. Describe what tools to interact with Git

**Comment by nopsg** [comment]
@DmitriyKulagin can you give more details, e.g the OS and version number?
