### ISSUE TITLE
Update azure docs

### ISSUE THREAD

**Issue by senneclaeskens** [nopSolutions/nopCommerce-Docs#41]
The documentation states:

> Run deploy.cmd to see if the default deploy script works locally. It should create an \artifact folder just outside of your git repository.

But by following all the previous steps, the deploy script returns this error:

> error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 form at, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

I think this is related to the fact that the deployment script is created by using 
`azure site deploymentscript --aspWAP`
instead of
`azure site deploymentscript --aspNetCore`

But that returns different errors. I'm currently checking on how to do it correctly.

**Comment by skoshelev** [comment]
Closed #41
