### ISSUE TITLE
Change the article about UPS 

### ISSUE THREAD

**Issue by skoshelev** [nopSolutions/nopCommerce-Docs#446]
we need to change [this article](https://docs.nopcommerce.com/en/getting-started/configure-shipping/shipping-providers/ups.html) to reflect changes in integration with the new [UPS API](https://github.com/nopSolutions/nopCommerce/issues/6712).

It would also be useful to add information about setting up the "shipment original location", since the lack of this information sometimes [causes difficulties](https://github.com/nopSolutions/nopCommerce/issues/6942#issuecomment-1856578753)

**Comment by DanwithArduino** [comment]
I'll make a fork.

**Comment by corymisc** [comment]
Is this related to the new UPS API changes that were announced and in effect on June 3 2024?

**Comment by DanwithArduino** [comment]
Yep. I've got a pull request open for documentation changes

**Comment by DmitriyKulagin** [comment]
Closed #446
