### ISSUE TITLE
'From' email doesn't always work 

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce-Docs#454]
> I believe that it's a useful information and nopCommerce team should mention the same in their documentation on this page https://docs.nopcommerce.com/en/getting-started/email-accounts.html#add-a-new-email-account for the "Email address" field, since I verified it on both Gmail and Outlook.
> You may write that, "some of the email providers may not use this setting unless this email address is added as an sending email alias / account in the email account which you're using for authentication".

Source: https://www.nopcommerce.com/boards/topic/100762/from-email-doesnt-work-easily-in-email-accounts-and-please-add-this-to-nopcommerce-documentation

**Comment by DmitriyKulagin** [comment]
Closed #454
