### ISSUE TITLE
Why does contributing require forking the repository?

### ISSUE THREAD

**Issue by tanveerbadar** [nopSolutions/nopCommerce-Docs#48]
Why does this [document ](https://docs.nopcommerce.com/developer/contribute/source-code.html#forking-and-submitting-pull-requests)says you should fork the repository and then submit a cross-repo pull request? What is the rationale behind that?

Normally, one creates a feature or bugfix branch in the same repository and submits a cross-branch pull request which ends up

* merging the changes into target branch
* optionally delete the source branch
* close the PR itself

**Comment by DmitriyKulagin** [comment]
The main advantage of the Forking Workflow is that contributions can be integrated without the need for everybody to push to a single central repository. Developers push to their own server-side repositories, and only the project maintainer can push to the official repository. This allows the maintainer to accept commits from any developer without giving them write access to the official codebase.
