### ISSUE TITLE
how-to-write-plugin_4.20.md - Missing csproj line

### ISSUE THREAD

**Issue by MadCoder253** [nopSolutions/nopCommerce-Docs#52]
Hi, 

I'm not certain but it looks like the following line is missing from the *.csproj example.

```xml
<ClearPluginAssemblies Include="$(MSBuildProjectDirectory)\..\..\Build\ClearPluginAssemblies.proj" />
```

**Comment by skoshelev** [comment]
Hi @MadCoder253. The necessary row of code exists, please see the screenshots

![Editing nopCommerce-Docshow-to-write-plugin-4 20 md at master · nopSolutionsnopCommerce-Docs - Google Chrome](https://user-images.githubusercontent.com/16875599/93059417-5671dd80-f679-11ea-9395-d8e8ae4011de.jpg)

![How to write a plugin for nopCommerce - Google Chrome](https://user-images.githubusercontent.com/16875599/93059502-74d7d900-f679-11ea-9011-d5a119bf15fd.jpg)
