### ISSUE TITLE
Replace old .aspx links with new ones

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce-Docs#55]
1. For example, https://docs.nopcommerce.com/user-guide/installing/faq.html has a link to https://www.nopcommerce.com/whychoose.aspx. Now it should point to https://www.nopcommerce.com/features
2. Premium support link at https://docs.nopcommerce.com/user-guide/installing/help.html
3. Any examples?

**Comment by DmitriyKulagin** [comment]
Closed #55
