### ISSUE TITLE
Improve font style for menu

### ISSUE THREAD

**Issue by jamestran1** [nopSolutions/nopCommerce-Docs#66]
The current menu does not look good
![image](https://user-images.githubusercontent.com/8802680/75070670-4e5c2000-5526-11ea-9d56-597e22afa6e0.png)

It should be improved to be good as this one:
![image](https://user-images.githubusercontent.com/8802680/75070740-7055a280-5526-11ea-9681-56822eb7a55f.png)

**Comment by AndreiMaz** [comment]
done
