### ISSUE TITLE
Example plugin .csproj file in documentation is flawed.

### ISSUE THREAD

**Issue by charagma** [nopSolutions/nopCommerce-Docs#88]
Example plugin .csproj for writing a plugin for nopCommerce 4.20 is flawed.

I've already made a PR - https://github.com/nopSolutions/nopCommerce-Docs/pull/86

1. ClearPluginAssemblies is not defined.
2. There is an extra space defining PluginPath property.

**Comment by skoshelev** [comment]
Fixed by https://github.com/nopSolutions/nopCommerce-Docs/commit/ff9c327f57a9e08aecd253a162e134f05b022aea
