### ISSUE TITLE
Update system requirements

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce-Docs#93]
See https://docs.nopcommerce.com/en/developer/tutorials/system-requirements-for-developing.html and https://docs.nopcommerce.com/en/installation-and-upgrading/technology-and-system-requirements.html

- Now Visual Studio 2019 is required (16.3 or above). Or Visual Studio Code with support of the latest version of C# extension

- .NET Core 3.1.201. SDK - https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.1.201-windows-x64-installer

- Hosting Bundle - https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-aspnetcore-3.1.3-windows-hosting-bundle-installer

- Specify minimum supported version of MySQL

--------------

Specify versions of .NET Core at https://docs.nopcommerce.com/en/installation-and-upgrading/technology-and-system-requirements.html (not specified now)

--------------

Update a version of supported IE browser at https://docs.nopcommerce.com/en/installation-and-upgrading/technology-and-system-requirements.html (we dropped IE 11 support in 4.30)

--------------

https://docs.nopcommerce.com/en/developer/tutorials/system-requirements-for-developing.html - 1. ".Net Core" should be written ".NET Core".
2. No hyperlinks to download .NET Core

**Comment by AndreiMaz** [comment]
@skoshelev updated the description with some notes

**Comment by skoshelev** [comment]
Closed #93
