### ISSUE TITLE
How to write a plugin for nopCommerce 4.30 (and above)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce-Docs#95]
Write a new article based on the existing one for 4.20 - https://docs.nopcommerce.com/en/developer/plugins/how-to-write-plugin-4.20.html

Once it's done do not forget to rename the menu title of "How to write a plugin for nopCommerce 4.20 (and above)" to "How to write a plugin for nopCommerce 4.20")

**Comment by skoshelev** [comment]
Closed #95
