### ISSUE TITLE
Update "Instruction on how to start developing on nopCommerce 4.2"

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce-Docs#97]
Article - https://docs.nopcommerce.com/en/developer/tutorials/instruction-on-how-to-start-developing-on-nopcommerce.html

We have to rewrite the article according to 4.30 changes

Furthermore, replace the first section ("Tools Required for Development") with a hyperlink to https://docs.nopcommerce.com/en/developer/tutorials/system-requirements-for-developing.html (duplicated)

**Comment by skoshelev** [comment]
Closed #97
